### ISSUE TITLE
SDGIO edges file change to JSON

### ISSUE THREAD

**Issue by mark-jensen** [SDG-InterfaceOntology/sdgio#100]
To enhance search functionality of the portal we need to include synonyms in the export file [sdgio-edges](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/reports/sdgio-edges.csv). For simplicity it was decided to make the export in JSON. 

The question remains as to whether to include ALL synonyms, or just EXACTs.

Once this is set up, we will need to update the [Wiki page](https://github.com/SDG-InterfaceOntology/sdgio/wiki/Links-to-UNEP-LIve) accordingly. 

@cmungall @pbuttigieg @kpmorris

**Comment by mark-jensen** [comment]
Related discussion [here](https://github.com/ontodev/robot/issues/70). 

This same file will also be used by Josephine Mule in generating the class info pages. Thus, it will serve as the main link in the build and release process from SDGIO on Git to UNEPLive.

In the JSON-formatted export, will we be only including a subset of properties? Or would it be easier to simply include everything?

The 3 portal-related utilities (search box, graph visualization, and class info pages) minimally require the following: Class IRI, label, definition, all synonyms, comment, object properties (both SGDIO native and imports), definition sources or xrefs.

**Comment by mark-jensen** [comment]
@cmungall @pbuttigieg Any ideas on timeline for implementation of this?

**Comment by cmungall** [comment]
Added jsonld export.

Some important points

## PURL

This JSONLD should *always* be accessed via a PURL. Do we have the nginx config in github yet? If so I can do this.

## JSON-LD

The export is a direct translation of the RDF/OWL model into JSON-LD, using a no-frills normalized translation. This means the representation is somewhat low-level - for example, anonymous class expressions are rendered as top level objects with blank node ID. To truly grok this you need to understand how OWL constructs are layered as RDF (and have a basic understanding of JSON-LD).

It may be better to use a higher level representation in future but I'm afraid I don't have time for this. It's not particularly hard for any developer who can find their way around the JSON-LD specs, I can recommend some people.

The ultra-quick hackers guide is:

 * classes will be objects of `@type` owl:Class
 * all `@id`s should be expanded using the map in the `@context`
 * NEVER EXPOSE A BLANK NODE. These are prefixed `_:`
 * the client code will need to do an extra lookup for all existential restrictions (non-isa edges). For example:

```
{
    "@id" : "sdg:SDGIO_00000017",
    "@type" : "owl:Class",
    "IAO_0000115" : "An exposure process in which an the processes executed by an entity are causally connected to those executed by a portion of contaminated environmental material.",
    "IAO_0000116" : "Draft def and class for demo purposes. The semantics of this class are being discussed and are very likely to change. Obsolescence is likely.",
    "label" : {
      "@language" : "en",
      "@value" : "exposure to contaminated environmental material"
    },
    "subClassOf" : [ "sdg:SDGIO_00000014", "_:b155" ]
  }

...

{
    "@id" : "_:b155",
    "@type" : "owl:Restriction",
    "onProperty" : "obo:RO_0000057",
    "someValuesFrom" : "obo:ENVO_00010483"
  }
```

corresponds to

```
SubClassOf(<http://purl.unep.org/sdg/SDGIO_00000017> <http://purl.unep.org/sdg/SDGIO_00000014>)
SubClassOf(<http://purl.unep.org/sdg/SDGIO_00000017> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/ENVO_00010483>))
```

**Comment by pbuttigieg** [comment]
Great stuff, thanks for pushing this through!
