### ISSUE TITLE
Classes from new domain ontologies

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#12]
Ontologies that would cover generally useful entities such as "war", "conflict", and "law" are not available for import into SDGIO.

Barry suggests that these should not be SDGIO classes and will reach out to those who can potentially develop such ontologies.

In the meantime there is likely to be a need for such classes. Comment on this issue with new term requests (NTRs) that are outside the domain of existing ontologies.

**Comment by mark-jensen** [comment]
@pbuttigieg Not sure what the status of this is. Or the milestone SDGIO Foundry. Ok to close?

**Comment by pbuttigieg** [comment]
Yes, I think we've moved on and can create new issues for NTRs. When an
"SDG Foundry" ontology pops up, we can obsolete and reimport.
