### ISSUE TITLE
Add the CGIAR IDOs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#133]
Following on from #130, we will now add the IDOs from the CGIAR Strategic Framework.

Definitions are not yet available. So, for the moment, we will add the IDOs as undefined classes. The MARLO Team has been asked to provide definitions.

**Comment by pbuttigieg** [comment]
Hi @Mttbnchtt 
We should create classes for an IDO itself, the actual IDOs will be instances of that class. In this case, the definitions are not as vital.

We also have to think about what an IDO actually is, and where it should sit in our top-level hierariches.

**Comment by pbuttigieg** [comment]
Merge with the Asana system's #135
