### ISSUE TITLE
Adding IDOs / phase 1

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#140]
I am starting adding the first 10 IDOs to the ontology. In phase 1:
(a) I will create a class for IDOs. The class will go under CGIAR organizational objective specification. 
(b) I will also add the first two IDOs (ID 1 and ID 2) to the new class. I will add the IDOs as instances if I understand how to do that. Otherwise, I will add them as sub-classes and change them to instances later.
(c) I will add some annotations to the IDOs as I find it in the CGIAR documents. However, there seems to be not much relevant information. (In particular, the MARLO team has already explained that IDOs does not have a definition. Apparently, their names are supposed to be clear enough.)

Soon after I completed phase 1, I will ask Pier Luigi to double check my work. Once I obtain his feedback, I will make the required corrections (if any) and insert the remaining 8 IDOs (from ID 3 to ID 10).

Two questions to clarify are:
1. whether we need to add the last 4 IDOs (ID A1, B1, C1, and D1), which refer to different SLOs than the three SLOs already added to the ontology. (See google doc Meeting Notes and Asana for more information.)
2. whether we need to dig out more information about the first 10 IDOs to have more or more complete annotations.

**Comment by Mttbnchtt** [comment]
I added an IDO class under CGIAR objective specification, i.e. under the same class where the sub-class SLO is. I also added a class sub-IDO under CGIAR object specification. 

The relevant trees are the following (I use a sort of "turtle" notation):
organisational objective specification/CGIAR objective specification/SLO
                                                                                                               /IDO
                                                                                                               /sub-IDO

**Comment by Mttbnchtt** [comment]
I am in the processes of understanding what the IDs for SLOs, IDO, and sub-IDOs ought to be. As soon as I know that, I will put that information in Protégé (and, if required, modify the SLOs entries as well).

**Comment by pbuttigieg** [comment]
@Mttbnchtt Please link all your issues to their corresponding PRs, such as #141

**Comment by Mttbnchtt** [comment]
We finished phase 1 of adding the IDOs to the ontology. I close this issue.
