### ISSUE TITLE
Clarify Xref of IDOs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#142]
#141 The IDs of the IDOs is not appropriate for the ontology since are mostly just integers. As @pbuttigieg suggested, based on the API CLARISA, we called them CLARISA:1, etc. Here is a snippet of CLARISA code: 
  {
    "code": "1",
    "description": "Increased resilience of the poor to climate change and other shocks",
    "isCrossCutting": false,
    "srfCrossCuttingIssue": null
  }

We need to verify whether the solution that we adopted is appropriate or we should change it. I will ask Elizabeth on the first occasion.

**Comment by pbuttigieg** [comment]
@elizabetharnaud

**Comment by marieALaporte** [comment]
Sounds good to me.
And maybe the CLARISA domain can be defined somewhere as clarisa.cgiar.org.
So eventually clarisa.cgiar.org/1 can dereference this specific IDO 1. I had a meeting few weeks ago with the MARLO team in the context of the CGIAR metadata WG, and discussed that the controlled terms that will be made available through clarisa should be accessible in that fashion

**Comment by Mttbnchtt** [comment]
Thanks @marieALaporte. Just to be sure, are you suggesting to use "clarisa.cgiar.org/1" as xref for the first IDO (and similarly for the others)? Or are you suggesting to ask the MARLO team or Elizabeth about this option?

**Comment by pbuttigieg** [comment]
@marieALaporte @Mttbnchtt 
I believe xrefs need to either be a full URL/IRI (with associated protocol, such as HTTP) or a CURIE-style ID.
So I assume this would be `https://clarisa.cgiar.org/1` ?

**Comment by marieALaporte** [comment]
I am fine with the CURIE style ID, CLARISA:1.
@pbuttigieg, where would we define the base URI (or URL) if we go for a CURIE style ID? 
@Mttbnchtt I am going to check with the CLARISA team that the base URL is https://clarisa.cgiar.org

**Comment by pbuttigieg** [comment]
>@pbuttigieg, where would we define the base URI (or URL) if we go for a CURIE style ID?

We'd have to create a mapping file somewhere. We usually use CURIE-style IDs when we can't find a good URI/IRI. The resolvable and dereferenceable IRI is very much preferred.

> @Mttbnchtt I am going to check with the CLARISA team that the base URL is https://clarisa.cgiar.org

Great, let's try to use these if we can

**Comment by marieALaporte** [comment]
in fact, it is more something like `https://clarisa.cgiar.org/api/srf-sub-idos/1.1.1`

Would that work?

**Comment by pbuttigieg** [comment]
Yes, that would be great.

**Comment by marieALaporte** [comment]
I can send to @Mttbnchtt the list of IDOs and sub-IDOs with the full API URL is this is useful??
@Mttbnchtt do you feel comfortable using the API directly or should I extract the content and save it as JSON or csv for you?

**Comment by pbuttigieg** [comment]
> I can send to @Mttbnchtt the list of IDOs and sub-IDOs with the full API URL is this is useful??

Very, please do. @Mttbnchtt: use these as the xref for the class.

> @Mttbnchtt do you feel comfortable using the API directly or should I extract the content and save it as JSON or csv for you?

It would be very useful to attach the list to this issue in CSV.

**Comment by marieALaporte** [comment]
This is a csv file that I had to save as text file for attaching it to the issue. 
It contains the URL of each IDO. The ones that are not numeric don't work, I don't know why.
Let me know if this is good. I can do the same for sub-IDOs

[IDOs.txt](https://github.com/SDG-InterfaceOntology/sdgio/files/3127271/IDOs.txt)

**Comment by pbuttigieg** [comment]
Great! Thanks @marieALaporte. A similar file for sub-IDOs would be very useful. @Mttbnchtt where would you like the sub-IDO.txt file to go? Do you have a dedicated issue for the sub-IDOs?

@Mttbnchtt use these as your xrefs. If changes are needed (due to the errors noted above) we can make changes in another PR.

I suggest @Mttbnchtt  creates a new issue about validating the URls that don't resolve (linking it to this one) so we can close this one.

**Comment by marieALaporte** [comment]
the sub-IDOs list is ready. @Mttbnchtt let me know where to attach it.

**Comment by Mttbnchtt** [comment]
Thanks a lot, @marieALaporte. I created issue #143 for the xref of sub-IDOs.

**Comment by pbuttigieg** [comment]
Great, @Mttbnchtt please close this issue when we've merged #141

**Comment by Mttbnchtt** [comment]
We have merged #141. Thanks to @pbuttigieg and @marieALaporte for your help. I close this issue now.
