### ISSUE TITLE
Xrefs for sub-IDOs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#143]
@marieALaporte could kindly add the CSV file with URLs for each sub-IDOs, as @pbuttigieg suggested. Thanks a lot.

**Comment by marieALaporte** [comment]
[sub-IDOs.txt](https://github.com/SDG-InterfaceOntology/sdgio/files/3127614/sub-IDOs.txt)

**Comment by Mttbnchtt** [comment]
Thanks, @marieALaporte. I will close this issue as soon as I finish working on the sub-IDOs.

**Comment by pbuttigieg** [comment]
Fixed in #153
