### ISSUE TITLE
Adding IDOs/phase 2

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#144]
I am starting to add the remaining 12 IDOs to the ontology. I plan to add all of them today 29 Apr 2019. There may something to care about the xref of some IDOs, but I will open another issue about that, if the case.

**Comment by pbuttigieg** [comment]
>There may something to care about the xref of some IDOs, but I will open another issue about that, if the case.

Hi @Mttbnchtt - be sure to cross-link the issues by referring to their #s
