### ISSUE TITLE
Non-fully-numeric codes for IDOs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#145]
In issue #142, @marieALaporte explained that the CLARISA codes of four IDOs is not fully numeric and it does work. When I enter a fully numeric code in the URL bar, I obtain the result in screenshot 1 (with URL https://clarisa.cgiar.org/api/srf-idos/1). When I enter a non fully numeric code in the URL bar, I obtain the error message in screenshot 2 (with URL https://clarisa.cgiar.org/api/srf-idos/D1). See the next comment for the files. 

I will clarify this issue with Marie-Angélique and report to @pbuttigieg.

**Comment by Mttbnchtt** [comment]
<img width="948" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/35274169/56910267-2623a200-6a78-11e9-9a59-4157e145bed7.png">
<img width="883" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/35274169/56910268-2623a200-6a78-11e9-805e-378c0982e9ca.png">

**Comment by htobon** [comment]
Hi Matteo, this is Hector from CLARISA.
I have just informed this issue to the technical team. In addition, please feel free to use the online chat we have in CLARISA in the bottom-left of the page to ask any questions or inform us that something is not working. If we are not online, we will read the message as soon as we are back.

**Comment by pbuttigieg** [comment]
Thanks for linking @htobon ! 
As @Mttbnchtt project matures, we'd like to explore how (with @marieALaporte's help) how results from SPARQL queries against SDGIO can lead on to gather useful data from CLARISA and other CGIAR systems. More soon!

**Comment by Mttbnchtt** [comment]
Thanks, Hector @htobon. If I understand what you say, we can use the non-fully numeric codes, since CLARISA is going to fix the error. Thanks for your help and the pointer to the CLARISA chat.

**Comment by htobon** [comment]
Yes, you are correct.

**Comment by mralmanzar** [comment]
Hi , this is Manuel from CLARISA.
we already made the correction of the error reported in the IDO's service.
please check it and let us know if something else is wrong.
King regards

**Comment by Mttbnchtt** [comment]
Hi @mralmanzar. Thanks very much to you and the CLARISA team for fixing the bug. I tried to test it, but I got a pop-up window requesting credentials that I do not have. So, I could not complete the test. However, as far as the ontology project is concerned, I think that things are fine for us. If @pbuttigieg is ok, I will close this issue.
