### ISSUE TITLE
Adding sub-IDOs/phase 1

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#151]

**Comment by Mttbnchtt** [comment]
➤ Matteo Bianchetti commented:

I am starting to add some sub-IDOs.

**Comment by Mttbnchtt** [comment]
In this phase, I merely add the sub-IDOs to the sub-IDO class. I am not going to consider here their relationship to IDOs.

**Comment by Mttbnchtt** [comment]
@marieALaporte and @pbuttigieg: I have added all the sub-IDOs to the IDO class as instances. There are 46 sub-IDOs. As DbXref I used the codes in the file _URLs of sub-IDOs_, which I have just uploaded to the MARLO google folder. Whenever you have time, you can review PR #153 and, if ready, merge it. Thanks very much.

**Comment by pbuttigieg** [comment]
#153 has been merged, I think we can close this issue.
