### ISSUE TITLE
Misspelling in label

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#154]
@marieALaporte 
@pbuttigieg 
The MARLO team used the following as label of a sub-IDO "Enhanced capacity to deal with climactic risks and extremes (Mitigation and adaptation achieved)". I think that 'climactic' should be 'climatic'.  'Climactic' does exist but it refers to an event being the climax of a series of events. This cannot be what the MARLO team mean here.  Is there some other specialized meaning of 'climactic' of which I am not aware and that makes it the right word here? Should I fix it?

This issue is related to the work done in the closed PR #151.

**Comment by pbuttigieg** [comment]
Sounds like a typo here

**Comment by Mttbnchtt** [comment]
I will fix it.

**Comment by Mttbnchtt** [comment]
The MARLO team confirmed that 'climactic' was a typo. I fixed it.
