### ISSUE TITLE
Links between SLOs, IDOs, and sub-IDOs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#155]
In this issue, we can upload the files describing the links between SLOs, IDOs, and sub-IDOs. @marieALaporte should be able to provide those files. With @pbuttigieg, I will use them to progress in the description of the three CGIAR modules.

**Comment by marieALaporte** [comment]
[linksIDOs-sub-IDOs.txt](https://github.com/SDG-InterfaceOntology/sdgio/files/3141498/linksIDOs-sub-IDOs.txt)
In this file, you can find the links IDOs-SubIDOS under the column srfIdoDTO.code

**Comment by pbuttigieg** [comment]
Is this done? @Mttbnchtt
