### ISSUE TITLE
Cross-cuttingness of issues or objectives

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#168]
The CGIAR SRF document describes some issues (or objectives) as cross-cutting. At p. 22, the SRF documents says: "Four issues cut across the whole research agenda". RIght now, the definition of CCO tries to capture the cross-cuttingness of these issues (or objectives) saying: " each research group contributes to its achievement". We need to (a) check that this interpretation is correct and (b) make it more precise (e.g. by specifying exactly which research groups we consider here).

**Comment by Mttbnchtt** [comment]
@pbuttigieg, in conversation, suggested making sure that the phenomena (e.g. "climate change " from ENVO) are in SDGIO and connect the cross-cutting objectives to them with axioms. He mentioned that the linkage structure will, itself, show them to be cross-cutting. I am not sure how the linkage structure will show the objective to be cross-cutting. However, I try to provide such a structure.

**Comment by Mttbnchtt** [comment]
@pbuttigieg Any suggestion on how to do this? E.g. "adapt to and mitigate climate change" is an instance of "CGIAR CCO". I suppose one could only use data properties to create axioms about this instance. However, we do not have any data property in SDGIO. What to do?

**Comment by pbuttigieg** [comment]
> "adapt to and mitigate climate change" is an instance of "CGIAR CCO"

This isn't an instance of just a CGIAR CCO. I think it should be split into three classes labelled
*  "planned process to adapt to climate change"
*  "planned process to mitigate the effects of climate change" 
*  "planned process to mitigate contributions to anthropogenic climate change" 

>He mentioned that the linkage structure will, itself, show them to be cross-cutting. I am not sure how the linkage structure will show the objective to be cross-cutting. However, I try to provide such a structure.

If a CGIAR plan (an instance) is an instance of many, thematically distinct categories (classes) of planned process categories, it is naturally cross-cutting.

**Comment by pbuttigieg** [comment]
> I suppose one could only use data properties to create axioms about this instance. However, we do not have any data property in SDGIO. What to do?

You can add it as an instance of multiple classes in the "Individuals by class" view:

![image](https://user-images.githubusercontent.com/2276146/61073289-65c21f00-a415-11e9-9297-f28c467c188c.png)
