### ISSUE TITLE
Inserting processes related to M1 into the ontology

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#169]
I add the processes related to the CGIAR module 1 and discussed [here](https://docs.google.com/spreadsheets/d/1g9Sp2Xmk8hVz5La1MBV9wJ2JIxo8WG4i_5TrfCPxOdM/edit#gid=0).

**Comment by pbuttigieg** [comment]
Many of these should be broken down into more atomic parts if possible.
Some of the longer labels should be instances of multiple atomic categories, rather than very specific categories themselves.

**Comment by Mttbnchtt** [comment]
@pbuttigieg Are you referring to terms like "planned process to increment the capacity of partner organizations to adopt research outputs"? This term currently denotes a process class. Are you saying that it should be an instance possibly of multiple classes? Could you give an example?

**Comment by Mttbnchtt** [comment]
We created processes classes.
