### ISSUE TITLE
What are poverty and poverty reduction for the CGIAR?

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#171]
@pbuttigieg @marieALaporte @elizabetharnaud 
The definition of SLO 1 (poverty reduction) and its related process (reduction of poverty) are unclear. The reasons are the following:
1. the ontology currently lacks a precise, or at least informative and reasonably objective, definition of poverty.
2. the ontology currently lacks a precise, or at least informative and reasonably objective, definition of reduction of poverty.

The first item is particularly confusing. For example, a quick check of the literature on poverty and poverty reduction uncovers the following widely different ways to define poverty: (a) income, (b) calories per day, (c) literacy, (d) life expectancy, (e) social exclusion. Moreover, each category may be approached in different ways (such: (a) annual income and (b) vulnerability to downward fluctuations of income). A search through thesauri like those at UN, World Bank, and Oxfam did not solve the issue. The CGIAR SRF document, which I consulted fist, also does not clarify this issue. 

What does CGIAR mean by "poverty" and "poverty reduction"?

**Comment by Mttbnchtt** [comment]
Among the various resources that one can find, the following one stands out: [UN MPI](https://feature.undp.org/multidimensional-poverty/). It stands out because it is a poverty index created by the UN and explicitly linked to the SDGs (see bottom of the page). However, I think we still need the CGIAR to explain what they take poverty to mean.

**Comment by Mttbnchtt** [comment]
@pbuttigieg 
@marieALaporte 
Let's see if the new definition of "process to reduce poverty" provides enough information to close this issue.

**Comment by pbuttigieg** [comment]
> Among the various resources that one can find, the following one stands out: UN MPI. It stands out because it is a poverty index created by the UN and explicitly linked to the SDGs (see bottom of the page). However, I think we still need the CGIAR to explain what they take poverty to mean.

I think this is a reasonable way to go for this ontology. If the CG don't have a more clear definition on what they mean, we will use this.

Please add a comment to the CG classes (at the instance-level especially) mentioning poverty, stating that we await a definition from their side and will default to the UN SDG definition in the meantime. 

I think we will need to add a set of classes to define the various dimensions of poverty. While this is outside the scope of your project, @Mttbnchtt, could you gather what you've found on this topic into an issue on the semantics of poverty?

**Comment by pbuttigieg** [comment]
Xref: https://github.com/SDG-InterfaceOntology/sdgio/pull/170#discussion_r302658804

#33 #64

**Comment by Mttbnchtt** [comment]
I added comments into the ontology. I will create an issue on poverty.

**Comment by Mttbnchtt** [comment]
I added the requested resources in issue #195.

**Comment by pbuttigieg** [comment]
@marieALaporte any input from the CG here?
