### ISSUE TITLE
Consistent labeling of planned processes

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#172]
@marieALaporte @pbuttigieg 
The labels of processes that have already been added to the _planned process_ class usually do not start with the term 'process'. I suppose that previous editors thought that doing so would have been redundant. However, in the M1 [draft](https://docs.google.com/spreadsheets/d/1g9Sp2Xmk8hVz5La1MBV9wJ2JIxo8WG4i_5TrfCPxOdM/edit#gid=0) we did begin every label of processes with the term 'process'. Should we adopt the previous editors' style for consistency and avoidance of redundancy? Or should we preserve our stylistic innovation perhaps for the sake of clarity of labeling?

**Comment by marieALaporte** [comment]
I would go with the old style as many ontologies are following it, but I am fine if we decide to change that and go for more clarity.

**Comment by Mttbnchtt** [comment]
@pbuttigieg suggested in a personal communication to use "planned process". I will close this issue for now, but more can be said when we review the PR #170.
