### ISSUE TITLE
Mitigation of agriculture effects on climate change

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#173]
@pbuttigieg @marieALaporte @elizabetharnaud 
Right now the definition of "process to mitigate climate change" is the following: "A planned process during which an agent causes or contributes to the mitigation of the effects of agro-ecosystems on the global climate system".

Which effects of agro-ecosystems are actually relevant here?

**Comment by pbuttigieg** [comment]
Outside my domain, unfortunately. 
If this is about agriculture, the label should reflect that. Right now it's too general. You should have something like:
* process to mitigate contributions to climate change
  * process to mitigate agricultural contributions to climate change

**Comment by Mttbnchtt** [comment]
Now we have: 

- planned process to mitigate contributions to anthropogenic climate change
     -  'planned process to mitigate contributions of agro-ecosystems to climate change'
'planned process to increase research capacity of organizations'
