### ISSUE TITLE
Conflict BFO and our ontology

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#175]
@pbuttigieg @marieALaporte 
The BFO guidelines say not to use acronyms in labels. However, our label for the processes associated to CC IDO C1 are the following: 
- "process to apply or improve institutional policies to increase the capacity of CGIAR partners to take actions concerning agriculture"
- "process to increase the research capacity of CGIAR national partners and beneficiaries".

Should we spell out CGIAR in full at the cost of making the label quite long?

**Comment by marieALaporte** [comment]
CGIAR is not an acronym. It used to be one but now it is just CGIAR.

**Comment by Mttbnchtt** [comment]
Got it, thanks. I removed the editor notes from those labels. The labels are consistent with BFO.
