### ISSUE TITLE
Break down complex objectives?

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#176]
@marieALaporte @pbuttigieg 
The labels of some CGIAR objectives contain conjunctions. For example: "adoption of technologies that reduce women's labor and energy expenditure". I wonder whether we ought to break entities of this type ought into their components, i.e. having the following two related sub-objectives:
- adoption of technologies that reduce women's labor
- adoption of technologies that reduce energy expenditure.

I see some virtue in having the atomic elements (of the appropriate ontological level) in the ontology if the composite elements are there.

**Comment by Mttbnchtt** [comment]
@marieALaporte 
@pbuttigieg 
Any input on this?

**Comment by pbuttigieg** [comment]
Yes, much better to break them down. Systems can annotate records with both IRIs if needed.

**Comment by Mttbnchtt** [comment]
Ok. I will do that after we close. pr #170.

**Comment by Mttbnchtt** [comment]
We broke down the processes. We decided not to change the objectives. We thought that it is better to keep the labels of the objectives as the CGIAR states them (with minor stylistic variations at most).
