### ISSUE TITLE
Adding "organization" from ENVO to SDGIO

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#179]
I committed a change of the envo_terms.txt to add "organization" from ENVO to SDGIO. @pbuttigieg will finalize the import before merging the PR #170.

**Comment by Mttbnchtt** [comment]
@pbuttigieg added _organization_ from ENVO to SDGIO. However, I have noticed that there is another class called _Organization_ in the Common Core Ontologies (CCOs). The two entries are distinct (different definitions, etc.). Which one should we import? Should CCOs take precedence over ENVO?

**Comment by mark-jensen** [comment]
I believe ENVO imports the term from OBI. The CCO version is derived from that one. We take a stronger stance and place it in the `object aggregate` branch, and remove some of the commentary in the OBI def. But, they are functionally equivalent, if not quite logically so. Thus, I’d stick with using the OBI one.

**Comment by mark-jensen** [comment]
PS, I think the term IRI should be added to the obi seed list, not the envo one.

**Comment by Mttbnchtt** [comment]
SDGIO currently has _organization_ with the following identifier: http://purl.obolibrary.org/obo/OBI_0000245. The term comes from OBI. 

@pbuttigieg is this issue solved?
