### ISSUE TITLE
PCO imports and term requests

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#185]
We should import terms from PCO to create the entries _human female_ and _young human_. We should also ask PCO to create the new terms _population of human females_ and _population of young humans_, which we will then import.

**Comment by Mttbnchtt** [comment]
@pbuttigieg 
@marieALaporte 

The PCO requires a new term request to provide the following pieces of information:
For new term requests, please provide the following information: (a) label, (b) synonyms, (c) definition, (d) suggested parent term. 

Let me try to start preparing these things.

1. 
Label: human female
Synonim: 'woman or girl' 
Definition: human being that, when of the appropriate age and healthy, is physiologically capable of bearing children. ([this](https://www.medicinenet.com/script/main/art.asp?articlekey=3408) says that the definition can be much more complicated, although, in the end, it does not provide one.)
suggested parent term: homo.

2. 
Label: young human
Synonim: 'girl or boy'
Definition: TBA
Parent term:  homo

3.
Label: population of human females
Synonim: none
Definition: a group of human females belonging to the population of some geopolitical entity. 
Parent term:  population

4.
Label: population of young humans
Synonim: vandals
Definition: TBA
Parent term:  population

5
Label: populace (from CCO Agent Ontology)
Synonim: population
Definition: A Group of Persons forming the total population of some Geopolitical Entity. (from CCO)
Parent term:  see CCO.

6. 
Label: geopolitical entity (import from CCO Agent Ontology).

Are these data ok? How to define young?

**Comment by Mttbnchtt** [comment]
Any input on this issue? Maybe @elizabetharnaud can provide the exact CGIAR definition of young humans.

**Comment by pbuttigieg** [comment]
I can see PCO having classes for the populations, but not necessarily the members (e.g. "young human"). Those can be axiomatised in the population definitions, however. 

I'm not sure we need to define young here, if we use the PATO quality. In fact, probably best to leave this open at the high-level and only specify this at the instance level.

**Comment by Mttbnchtt** [comment]
@pbuttigieg If I understand, you are saying not to request new terms from PCO. I do not understand what to do with PATO (?) or else.

**Comment by Mttbnchtt** [comment]
@pbuttigieg imported the following terms from PATO: female, male, mature, immature, juvenile, adolescent, prepubescent, pubescent, neonatal, increased tolerance to, decreased tolerance to, normal tolerance to, normal, abnormal, increased resistance to, decreased resistance to, normal resistance to, decreased functionality, increased functionality, non-functional, necessary (continuant), unnecessary (continuant), active, constitutively active, inactive, mild intensity, moderate intensity, severe intensity, increased intensity, decreased intensity, remittent intensity, profound intensity. 

@pbuttigieg imported power plant, habitat, forest, aquifer, wetland, mountain from ENVO.

**Comment by cmungall** [comment]
See also http://obofoundry.org/ontology/hsapdv has developmental stages but also adult
