### ISSUE TITLE
CCO imports

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#186]
The following are some terms that I would like to import from CCO:
1. [agent](http://www.ontologyrepository.com/CommonCoreOntologies/Agent)
2. [group of persons](http://www.ontologyrepository.com/CommonCoreOntologies/GroupOfPersons)
3. [group of organizations](http://www.ontologyrepository.com/CommonCoreOntologies/GroupOfOrganizations)
4. [person](http://www.ontologyrepository.com/CommonCoreOntologies/Person)

There is an observation:
(a) Importing 'person' will import 'organism', the definition of which conflicts with [organism](http://purl.obolibrary.org/obo/OBI_0100026) in OBI, which is already present in SDGIO. Is that a problem? If yes, what to do about that?

@marieALaporte 
@pbuttigieg

**Comment by pbuttigieg** [comment]
The CCO material looks reasonable, but I don't think they work well with our tooling (@cmungall ?)

for Person:
```
###  http://www.ontologyrepository.com/CommonCoreOntologies/Person
cco:Person rdf:type owl:Class ;
           rdfs:subClassOf cco:Animal ;
           cco:alternative_label "Human"^^xsd:string ;
           cco:definition "An Animal that is a member of the species Homo sapiens."^^xsd:string ;
           cco:definition_source "https://en.wikipedia.org/wiki/Human"^^xsd:string ;
           cco:is_curated_in_ontology "http://www.ontologyrepository.com/CommonCoreOntologies/Mid/AgentOntology"^^xsd:string ;
           rdfs:label "Person"^^xsd:string .
```

Why not just use "Homo sapiens" (NCBITaxon_9606) which is already imported? "Person" is more a legal entity anyway.

**Comment by pbuttigieg** [comment]
For now, create classes in SDGIO if we can't import then from other OBO resources. 
Add editor note(s) with the IRIs of any CCO classes you think we should align to or consider importing (if feasible).

**Comment by Mttbnchtt** [comment]
@pbuttigieg Are you saying to add now agent, group of persons, group of organizations, and person? Or are you saying to leave out everything that has to do with the concept of a person? If the latter, I may introduce the following classes: agent, group of agents, group of organizations. Let me know what you meant.

**Comment by Mttbnchtt** [comment]
Either add "agent" (if we find a good definition) or add axioms "organization or homo sapiens" wherever we use "agent" in the definition of the relevant item.

**Comment by Mttbnchtt** [comment]
Added 'has part' some ('Homo sapiens' or organization).
