### ISSUE TITLE
Link objectives via processes

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#187]
In this [issue](https://github.com/information-artifact-ontology/IAO/issues/214), @pbuttigieg discussed how to related objectives among themselves using processes. Here I give an example to see if this is indeed how we want to proceed.

Let us consider IDO B1 "achieve equity and inclusion" and show that it is a subgoal of SLO 1 "reduce poverty".

To achieve IDO B1, there are two processes:
(a) planned process to improve the capacity of women to participate in decision making
(b) planned process to improve the capacity of young people to participate in decision making.

To achieve SLO 1, there is one process:
(c) planned process to reduce poverty.

We say: 
1. (a) concretizes IDO B1
2. (b) concretizes IDO B1
3. (c) concretizes SLO 1
4. (a) is part of (c)
5. (b) is part of (c).

Is that correct? Is it all?.

@marieALaporte may also be interested.

**Comment by pbuttigieg** [comment]
Xref https://github.com/obi-ontology/obi/issues/1033
Xref https://github.com/information-artifact-ontology/IAO/issues/214

>(a) is part of (c)
(b) is part of (c)

Yes, that's how we can nest processes, and thus the objectives they're linked to.


> (a) concretizes IDO B1
(b) concretizes IDO B1

See the elucidation on "concretizes" here: http://purl.obolibrary.org/obo/RO_0000059
It's very convoluted and we need something more clear. That may be fun for ontologists, but not sure it will be useful for users of the SDGIO. 

For the moment:

The current equivalence axiom on `planned process` is:

```
planned process equivalentClass : realizes some concretizes some plan specification
```
http://purl.obolibrary.org/obo/OBI_0000011


As objective specifications are parts of plan specifications we can say:

An objective O is  'part of' some ('plan specification' and 'is concretized as' some 'realized in' some 'planned process X')

**Comment by Mttbnchtt** [comment]
That sounds a good idea. My use of _concretizes_ was wrong since the definition defines it between two continuants but processes are occurrents.

**Comment by Mttbnchtt** [comment]
Got it. I will add these new items after PR #170 is closed.

**Comment by Mttbnchtt** [comment]
I observed that @pbuttigieg linked some objectives to some processes via axioms of the form _is about some (process)_ given to the objectives. I will continue doing that after we close PR #170.
