### ISSUE TITLE
Outcomes and key outputs CGIAR module 1

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#188]
In the CGIAR module 1, we have 4 outcomes and 8 key outputs. I describe one outcome and one output to start discussing how to represent those entities in the ontology.

Let us consider outcome 1:  
(O) a demand-driven analytics environment is available.

Let us consider key output 1:
(K) prototype backend tools and services (at least 2) to leverage data for analysis/ visualization.

We also have the  following : 
(R1) K --> O
(R2) O--> sub-IDO D1.1 (enhance institutional capacity of partner research organizations).

Step 1. Clarify what the arrows mean. Is it _part of_ in both cases? @marieALaporte  may be particularly knowledgeable about this.

Step 2. Reformulate:
(O') make available a demand-driven analytics environment
(K') make available at least two prototypes back-end tools and services to leverage data for analysis or visualization.

Step 3. Clarify what the environent and prototypes are. 

Step 4. Clarify how to describe environment and prototypes in the ontology. The environment is GARDIAN. Is this a software or a database or a repository of databases? What about prototypes? Should these items be instances (as I suppose) or classes?

Step 5. Import terms from other ontologies to describe O' and K'. IAO has "software" and "database extract", which may be interesting. There are probably also other terms to consider. Neither BFO nor IAO have "database". 

Step 6. Describe the relations among O, K, and sub IDO D1.1. If we can use the part-of relation between instances, this may straightforward. Otherwise, we will need some more thinking.

I ask whether @marieALaporte and @pbuttigieg can help.

**Comment by elizabetharnaud** [comment]
I am fine with the step2. for step 3: we need to look at the deliverables of Module#1 in MARLO that contributes to the  prototypes  of a driven driven analytics environment.

**Comment by pbuttigieg** [comment]
@Mttbnchtt there's a chance we will address another CRP on instruction from Brian et al. 
Hold off on these KOs right now.

Recall, we're likely to have very general classes for these, hosting the particulars as instances.

**Comment by Mttbnchtt** [comment]
@marieALaporte Is this discussion out-of-date, given the new direction of the project? If yes, feel free to close the issue.

**Comment by Mttbnchtt** [comment]
We do not work on KOs.
