### ISSUE TITLE
Deliverables and projects under key outputs

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#191]
On the MARLO website, there are different deliverables and projects listed under each key output. For module 1, we have 83 deliverables and roughly 40 projects for 8 key outputs. The deliverables change every year. I am not sure about how often projects changes. Both deliverables and projects come with decently exhaustive descriptions. So, if we put them in the ontology, we should have enough information to give them descriptive labels, add informative notes, and add a proper xref. 

Question 1: should we add deliverables into the ontology?
Question 2: should we add projects into the ontology?

What do @marieALaporte and @pbuttigieg think?

**Comment by pbuttigieg** [comment]
We would have to ask if there's any utility in adding the deliverables and projects.

My instinct is not to add these to an ontology like SDGIO (which deals with the higher-level strategic directives). They would be more useful in CGIAR project management solutions.

That being said, they can of course be linked to the higher-level DOs as needed, using SDGIO IRIs, This would allow different project management solutions in the Big Data for Ag's ecosystem to interoperate on the DO level.

**Comment by marieALaporte** [comment]
I agree with @pbuttigieg, I don't think they should be added in the ontology.
This part could be handled separately (maybe in the MARLO dashboard, although I am really not sure if this would be the ideal place for that).
