### ISSUE TITLE
Set up PURLs

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#2]
SDGIO PURLs should be similar to the form:
http://purl.un.org/sdg/SDGIO_00000001

There may be a need for a PURL server to be hosted by UNEP to secure http://purl.un.org/

**Comment by pbuttigieg** [comment]
UNEP will set up their own PURL server and issue PURLs with the root: 
http://purl.unep.org/

We would then need to issue PURLs for each SDGIO class resembling:
http://purl.unep.org/sdg/SDGIO_00000001

@cmungall, @mcourtot: Since this is outside the OBO Library system, what would need to be done to bridge the classes that will be created in sdgio.owl to the UNEP PURLs?

**Comment by mcourtot** [comment]
The page at https://code.google.com/p/obo-foundry-operations-committee/wiki/OBOPURLDomain details the OBO setup. 
I'm not entirely sure what you mean by "bridge the classes that will be created in sdgio.owl to the UNEP PURLs".  If you mean HTML resolution, you need to setup a system allowing you to do so. 
You need:
(1) The PURL server redirecting everything under http://purl.unep.org/sdg/ somewhere. In our case we use the Berkeley server as in intermediate step, but you could probably just go directly to where your HTML pages would be. We use a partial redirect from the domain itself (e.g., all the IDs as you obviously don't want to create one PURL per ID), and specific links towards specific items, e.g. the latest stable version of the released file. In your case maybe http://purl.unep.org/sdg/sdgio.owl could be the stable PURL always pointing to the latest release.
(2) For HTML resolution we use Ontobee, which can be downloaded and set up as its own instance - see https://github.com/ontoden/ontobee - though I don't know how easy it is to do as I never tried myself. Alternative options...you could perhaps generate your own HTML independently by script, similar to what we use to do with OB? Note that in both cases the HTML was the front end for human readers, but the source would be RDF for machine consumption.
I hope this helps, happy to chat more if desired.

**Comment by cmungall** [comment]
On 6 Aug 2015, at 7:38, Melanie Courtot wrote:

> The page at 
> https://code.google.com/p/obo-foundry-operations-committee/wiki/OBOPURLDomain 
> details the OBO setup.

(note this page will become readonly soon, we need to redirect it before 
it becomes too late to do this)

> I'm not entirely sure what you mean by "bridge the classes that will 
> be created in sdgio.owl to the UNEP PURLs".  If you mean HTML 
> resolution, you need to setup a system allowing you to do so.
> You need:
> (1) The PURL server redirecting everything under 
> http://purl.unep.org/sdg/ somewhere. In our case we use the Berkeley 
> server as in intermediate step, but you could probably just go 
> directly to where your HTML pages would be. We use a partial redirect 
> from the domain itself (e.g., all the IDs as you obviously don't want 
> to create one PURL per ID), and specific links towards specific items, 
> e.g. the latest stable version of the released file. In your case 
> maybe http://purl.unep.org/sdg/sdgio.owl could be the stable PURL 
> always pointing to the latest release.
> (2) For HTML resolution we use Ontobee, which can be downloaded and 
> set up as its own instance - see https://github.com/ontoden/ontobee - 
> though I don't know how easy it is to do as I never tried myself. 
> Alternative options...you could perhaps generate your own HTML 
> independently by script, similar to what we use to do with OB? Note 
> that in both cases the HTML was the front end for human readers, but 
> the source would be RDF for machine consumption.

Things are definitely much easier if we stick with OBO purls. There is 
nothing to stop there being "backup purls" at the UNEP that could mirror 
or redirect to the content of the OBO purl

**Comment by pbuttigieg** [comment]
Thanks @mcourtot, @pdez90 is setting up the UNEP server. 

@pdez90 I'd imagine you'd want an OntoBee-like set-up to resolve PURLs (e.g. http://purl.obolibrary.org/obo/ENVO_01000280)? With more time and resources, you could perhaps transition to something more like CHEBI's setup (e.g. http://purl.obolibrary.org/obo/CHEBI_28938) in the future.
That being said, @cmungall is right that using OBO PURLs would allow faster development of the ontology. @cmungall what kind of overhead would we incur if we used UNEP PURLs?

**Comment by pbuttigieg** [comment]
@jamesaoverton wondering if you have a moment to comment on this thread::
Would you have any advice on how much development time would go into setting up  a new instance of OntoBee? The objective here is to get a PURL server set up for UNEP so they can resolve class URLs (of the form http://purl.unep.org/sdg/SDGIO_00000001) for the SDGIO project.

**Comment by jamesaoverton** [comment]
Ontobee is a PHP application backed by a Virtuoso triplestore. Old [source code is available](https://github.com/ontoden/ontobee) but it's not well documented. I spent a couple of days last year stripping it down and getting basic things working, mostly through trial and error. That deployment code is here: https://github.com/jamesaoverton/ontoden-deploy

Given that, it shouldn't be too hard to get your own Ontobee running, especially if you have someone familiar with PHP and with at least a little familiarity with SPARQL. But I would not say that it's easy (unfortunately).

**Comment by cmungall** [comment]
Do you happen to know if there are any hardcoded assumptions about PURL structure? The goal here is to set up a parallel instance in order to use non-OBO purls?

@pbuttigieg there may be other complications awaiting. If you want to mirror the (IMHO, fragile) OBO setup, you actually need 3 servers:

 1. A purl server (*or* you can use OCLC with sufficient redirects)
 2. OntoBee
 3. An addition apache server for dealing with a redirect issue

Why is the 3rd one necessary? Good question, it's partly to do with the structure of OBO purls (use of the underscore to divide the authority from the ID fragment). This is somewhat described here: http://obofoundry.github.io/docs/OBOPURLDomain.html

Additionally you'll be working from what is not great documentation (though we aim to improve it). You should be sure to allocate sufficient resources at the UN side to manage this.

At this stage it might be useful to backup and do some requirements analysis. I believe this has been excellent for the ontology *content* which is the most important thing. But has there been any analysis done on requirements for things like ontology and class PURLs? Even if you persevere with the above URL architecture, the resulting OntoBee page you get is let's face it a bit geeky for the average non-OWL person (of course this would be short term and the unep purls could resolve to a custom website in time).

**Comment by jamesaoverton** [comment]
@cmungall The main Ontobee instance includes non-OBO ontologies. Here's an example of a non-OBO class: <http://www.ontobee.org/browser/rdf.php?o=EDAM&iri=http://edamontology.org/data_2363>. There are other hardcoded assumptions that I had to work around, but non-OBO PURLs should be fine.

But I agree that the OBO setup is not an ideal starting point for a simple project. If you can get away with a basic web server with static pages at the right PURL for each term, that would be *much* simpler to setup and maintain.

**Comment by cmungall** [comment]
I second the static page idea

owltools can be used to generate a pretty rough static site in markdown format; e.g.:

https://github.com/obophenotype/cephalopod-ontology/blob/master/src/ontology/md/CEPH/56/CEPH_0000256.md

Seeing everything embedded in the github interface makes this a bit geeky. It wouldn't be too hard to do something smarter using github pages for a nicer look and feel.

I wouldn't use the owltools md writer as a starting point though; a more declarative JVM language would be ideal.

**Comment by pbuttigieg** [comment]
Thanks for the input and advice @jamesaoverton and @cmungall!

@pdez90 - As you can see, independent set-up is non-trivial. The static page solution looks attractive as it's relatively straightforward and you also have quite a bit of freedom in what the pages look like etc. You can still use the PURL server at OCLC in the short- to mid-term and then set up your own server to handle redirects to the pages associated with each class.

**Comment by pdez90** [comment]
Thanks so much all! Your comments have been really useful. I've just
downloaded https://sites.google.com/site/persistenturls/ in order to set up
a server and issue purls with the un top level domain- and once the server
is up and running will figure out how to upload the static webpages. That
does seem much easier than getting our own Ontobee up and running for the
moment. Thank you for all your help!

On Mon, Aug 10, 2015 at 1:29 PM, Pier Luigi Buttigieg <
notifications@github.com> wrote:

> Thanks for the input and advice @jamesaoverton
> <https://github.com/jamesaoverton> and @cmungall
> <https://github.com/cmungall>!
>
> @pdez90 <https://github.com/pdez90> - As you can see, independent set-up
> is non-trivial. The static page solution looks attractive as it's
> relatively straightforward and you also have quite a bit of freedom in what
> the pages look like etc. You can still use the PURL server at OCLC in the
> short- to mid-term and then set up your own server to handle redirects to
> the pages associated with each class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-129399543>
> .
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by pdez90** [comment]
Dear all,

The IT guys at UNEP have set up our purl server:
http://purl.unep.org/docs/index.html

I just thought you'll would like to know!
I have created the domain /sdg/

On Mon, Aug 10, 2015 at 1:48 PM, Priyanka deSouza <priyankadesouza@gmail.com
> wrote:

> Thanks so much all! Your comments have been really useful. I've just
> downloaded https://sites.google.com/site/persistenturls/ in order to set
> up a server and issue purls with the un top level domain- and once the
> server is up and running will figure out how to upload the static webpages.
> That does seem much easier than getting our own Ontobee up and running for
> the moment. Thank you for all your help!
>
> On Mon, Aug 10, 2015 at 1:29 PM, Pier Luigi Buttigieg <
> notifications@github.com> wrote:
>
>> Thanks for the input and advice @jamesaoverton
>> <https://github.com/jamesaoverton> and @cmungall
>> <https://github.com/cmungall>!
>>
>> @pdez90 <https://github.com/pdez90> - As you can see, independent set-up
>> is non-trivial. The static page solution looks attractive as it's
>> relatively straightforward and you also have quite a bit of freedom in what
>> the pages look like etc. You can still use the PURL server at OCLC in the
>> short- to mid-term and then set up your own server to handle redirects to
>> the pages associated with each class.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-129399543>
>> .
>>
>
>
>
> --
> Yours Sincerely,
> Priyanka deSouza
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by pbuttigieg** [comment]
Links to #26.
@pdez90 do you think this issue has been addressed? If so, we can close it.

**Comment by pdez90** [comment]
Pier, give Josephine and I today and we will report back this evening. We
are having a bit of trouble with the purls (we're trying to get rid of the
tombstoned purls)

Thanks!

On Mon, Oct 12, 2015 at 6:15 PM, Pier Luigi Buttigieg <
notifications@github.com> wrote:

> Links to #26 <https://github.com/SDG-InterfaceOntology/sdgio/issues/26>.
> @pdez90 <https://github.com/pdez90> do you think this issue has been
> addressed? If so, we can close it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-147429806>
> .
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by cmungall** [comment]
You have to be careful with the purl server. In general, it's a very bad 
idea to tombstone/delete purls. It can be very hard to retrieve, and you 
can't reuse the same purl.

I have a feeling that using the purl server may be overkill for UNEP 
purposes. You can do the same thing with no real downsides using a 
simple apache/nginx/etc setup. I would have to see the full requirements 
to be sure.

**Comment by pdez90** [comment]
Hi Chris, We've got the purl server reinstalled. We won't tombstone purls
now, but modify them to 410- permanently gone. I think this should work as
well.
Im not sure what you mean about the functionality of that kind of set up.
If you could give us an example, that would be great!

On Fri, Oct 16, 2015 at 5:18 AM, Chris Mungall <notifications@github.com>
wrote:

> You have to be careful with the purl server. In general, it's a very bad
> idea to tombstone/delete purls. It can be very hard to retrieve, and you
> can't reuse the same purl.
>
> I have a feeling that using the purl server may be overkill for UNEP
> purposes. You can do the same thing with no real downsides using a
> simple apache/nginx/etc setup. I would have to see the full requirements
> to be sure.
>
> On 14 Oct 2015, at 3:44, Priyanka deSouza wrote:
>
> > Pier, give Josephine and I today and we will report back this evening.
> > We
> > are having a bit of trouble with the purls (we're trying to get rid of
> > the
> > tombstoned purls)
> >
> > Thanks!
> >
> > On Mon, Oct 12, 2015 at 6:15 PM, Pier Luigi Buttigieg <
> > notifications@github.com> wrote:
> >
> >> Links to #26
> >> <https://github.com/SDG-InterfaceOntology/sdgio/issues/26>.
> >> @pdez90 <https://github.com/pdez90> do you think this issue has been
> >> addressed? If so, we can close it.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-147429806
> >
> >> .
> >>
> >
> >
> >
> > --
> > Yours Sincerely,
> > Priyanka deSouza
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-148010193
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-148577394>
> .
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by cmungall** [comment]
I think you should reconsider your use of the persistent URL software solution and adopt a simple apache setup configured via github. Note that OCLC is abandoning its purl server, the future of the software underpinning it is in doubt.

In any case it's over the top and too complex for what we need here.

**Comment by mark-jensen** [comment]
@pdez90 @cmungall @pbuttigieg 
Has a decision been made re how best to resolve the PURLs?

**Comment by pdez90** [comment]
Hi,

Im sorry I just saw this. I was on break during the time the above was
posted.
 I have copied Josephine here. We will examine how best to do this.

On Thu, Dec 3, 2015 at 4:21 AM, Mark Jensen <notifications@github.com>
wrote:

> @pdez90 <https://github.com/pdez90> @cmungall
> <https://github.com/cmungall> @pbuttigieg <https://github.com/pbuttigieg>
> Has a decision been made re how best to resolve the PURLs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SDG-InterfaceOntology/sdgio/issues/2#issuecomment-161485936>
> .
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by mark-jensen** [comment]
@pbuttigieg Closing this for now.
We may have still have some small issues to resolve for versioning, but that can taken up in new issue when needed.
