### ISSUE TITLE
Expressing vulnerability 

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#200]
Vulnerability as a disposition applies universally: e.g. all humans are vulnerable to drowning. 
However, vulnerable communities in the narratives of development are those with a higher chance or a past history of realising these dispositions.

Expressing this needs a pattern, perhaps leveraging BFO:history

#22 #199

**Comment by pbuttigieg** [comment]
For now, we're oversimplifying and stating the following for vulnerable communities etc:

'has participant' some ('collection of humans' and 'has disposition' some vulnerability)

**Comment by Mttbnchtt** [comment]
> For now, we're oversimplifying and stating the following for vulnerable communities etc:
> 
> 'has participant' some ('collection of humans' and 'has disposition' some vulnerability)

Axiom added. I leave this issue open because @pbuttigieg mentioned that the solution needs refinement.

**Comment by marieALaporte** [comment]
This axiom should be added to the processes involving vulnerable communities, not to 'vulnerability' directly

**Comment by Mttbnchtt** [comment]
Better not, since "vulnerable community" is already a subclass of "collection of humans".
