### ISSUE TITLE
IDO 3: income and employer

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#206]
#201 

I wonder whether we want to add _income_ and related terms like _money_ into the ontology to describe the process _development of capacity to increase income_, which is related to IDO 3.

For the process to increase employment: should we add _employer_?

**Comment by Mttbnchtt** [comment]
For completeness, I recall here that @pbuttigieg in #201 mentions that, for IDO 3, we also need _economic sector_ and _agricultural sector_.

**Comment by Mttbnchtt** [comment]
Use _human employer_. 
Create _income_ under _asset_.

**Comment by Mttbnchtt** [comment]
Let's wait for @pbuttigieg's explanation on where to put economic sector and agricultural sector.

**Comment by Mttbnchtt** [comment]
@pbuttigieg explains to create "socio-economic system" under "system".  

Pier Luigi said the following: Then subclasses like "agricultural socio-economic system", which would be synonymous with the ag sector (the system of people, environments, and manufactured products engaged in agricultural activities or something like that). Economic sector would be synonymous with the socio-economic system. Not sure if we want to split socio-  and economic into their own systems (I don't think you can have one without the other, but please read around that topic).

**Comment by Mttbnchtt** [comment]
I added:
1. socio-economic system
    ... agricultural socio-economic system (synonim: agricultural sector)
2. economic system (synonim: economic sector)

In a sense, economic factor are social factors economy is a social science. In another narrow sense, social factors (like one's social status) are not not economic factors (a noble can be poor and have, nevertheless, high social status). I composed the classes above taking "social factor" to have a narrow meaning.

**Comment by marieALaporte** [comment]
@Mttbnchtt according to Pier's comment, 'economic sector' should be a synonym of 'socio-economic system'. 'economic system' can thus be removed

**Comment by pbuttigieg** [comment]
> Ok with me, but then I should not import "market" from ENVO. If services are not goods (as I also wondered in #205), then ENVO is wrong for the reason explained in the first comment of issue #205 (note that the part of the first comment in that issue that do not refer to services are mostly out-of-date, since @marieALaporte has given further useful directions). In that case, I should ask ENVO to change the definition of market. Should I do that?

ENVO:market is referring to a physical gathering of stalls etc. That's a different entity from the "market" used here. We'll need a new class for that, probably in SDGIO itself.'

> Ok. However, we need something that says that not only agents consistute an economic system. I will think about a better way to do that.

Yes, it's tricky, but try to find a more general way of capturing that.

> Ok. Are lists in definitions acceptable if introduced by "for example" as ENVO's deforestation?

Yes, that's better as it shows that the list is not meant to be exhaustive, just illustrative.

> So, for me, it was ok to follow that previous suggestion of yours and have "economic sector" as a synonim of "economic system". Are you now saying that, on reflection, it is better to do otherwise and speak only of "economic system"?

Yes and no: I think the sector is more granular than the system. An economic sector would be a kind of economic system where interactions are concentrated over a defined set of goods and services. However, there's the very high-level parsing of "economic system" (capitalist, socialist, syndicalist, etc).

Let's try sectors (ag, econ, socio, etc) as subclasses of system for now They would be siblings of classes like "economic system" which would have subclasses like "capitalist economic system".

We'll refine when we have more material on this theme.

**Comment by Mttbnchtt** [comment]
I inserted "socio-economic system" and "economic system". I have not inserted sectors yet. I want to check with Marie-Angélique whether and how to insert those terms. They are rather complicated to define and position and maybe they are not really useful now.

**Comment by Mttbnchtt** [comment]
For now, we just add socio-economic system, agricultural socio-economic system, and economic system. We add economic sector and agricultural sector as synonims of some of the items mentioned before.
