### ISSUE TITLE
IDO 4: productivity, capacity, and resilience

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#207]
For IDO 4, @pbuttigieg indicated that we need _productivity_, _economic productivity_, and _capacity_. Concerning the last term, we need it for most of IDOs.

Concerning the first two terms, the NCIT ontology has _[productivity](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C86582
)_, which they define as follows: "The ratio of the quantity and quality of units produced to the labor per unit of time." They put _productivity_ under _power or attribute_, however, @pbuttigieg suggests to put it under _disposition_.

Moreover, the defifnition of _productivity_ of the NCIT is focused on economic productivity, unless ones takes _labor_ to indicate any process, including wholly natural ones. 

@marieALaporte: do you think we could use the NCIT item changing its label to _economic productivity_? Or we should just create a different item for SDGIO?

**Comment by Mttbnchtt** [comment]
@pbuttigieg @marieALaporte 
Concerning the item _capacity_, we have to distinguish at least between capacity in the sense of volume (or something similar: the bottle's capacity is 1L) and capacity in a sense close to disposition, power, or ability (something expressed by some sense of the verb _can_: she can understand French). Only the second sense is relevant to us. 

The OED takes capacity to be an ability, while NCIT takes in the first sense. This [SEP](https://plato.stanford.edu/entries/abilities/) article tentatively suggests the hierarchy: ability _is a_ power _is a_ capacity (where the other direction does not hold for any of those items). 

Putting together the SEP article and Cartwright's _Nature's capacities_, one could say that (a) capacities are something that is typically expressed by the modal 'can' taken to express not a mere possibility or probability; (b) something that can be triggered, shielded, enhanced, interfered with, and the like; (c) something that not only individuals have (contrary to powers, which are capacities that only individuals have).

This is still not a definition though. Any suggestions?

**Comment by marieALaporte** [comment]
@Mttbnchtt It is not good practice to change the label (or any other property) of an imported term. 
As the semantics of NCIT is a bit tricky and doesn't align well with what we have in SDGIO, I would recommend creating a term directly in SDGIO. You can reference the NCIT class as source for the definition if you think that's useful.

**Comment by Mttbnchtt** [comment]
@marieALaporte: sounds good. Thanks. 

Concerning _resilience_, see #203.

**Comment by Mttbnchtt** [comment]
The SDGIO definition of productivity could be: ratio of output (goods, productis, etc.) per unit of input (labor, material, equipment, etc.). 

While NDCIT restricts input to labor (and thus ends up defining economic productivity rather than productivity), we are more general. What do you think?

**Comment by Mttbnchtt** [comment]
We create our definitions of productivity and economic productivity.

**Comment by Mttbnchtt** [comment]
I added productivity, economic productivity, and capacity.

**Comment by Mttbnchtt** [comment]
In #201, what does it mean that development of capacity to increase agricultural productivity can be post-composed? How?

**Comment by Mttbnchtt** [comment]
> In #201, what does it mean that development of capacity to increase agricultural productivity can be post-composed? How?

It can be done, when needed, at the instance level. We do not create this process class for now.
