### ISSUE TITLE
Increase capacity or something else?

### ISSUE THREAD

**Issue by Mttbnchtt** [SDG-InterfaceOntology/sdgio#212]
As I started noting in #201, some IDO-related processes are not clearly processes to improve a capacity. 

For example, IDO 3 is _increase incomes and employment_. In our categorization, one corresponding process becomes _proess to increase capacity to increase incomes_. I am not worried about the label being inelegant. The point is that the label may indicate something wrong. The process ought to increase incomes, not capacity to increase incomes. 

An issue of the same type hold for IDO 4, 5, 6, 7, 10, and possibly 2 , 8, and 9. I have not considered the cross-cutting IDOS for now.

**Comment by Mttbnchtt** [comment]
@marieALaporte explained that the CGIAR only increases the capacity of someone or something else to do something. So the labeling is appropriate as it is now.

**Comment by elizabetharnaud** [comment]
We could discuss this point with Julien and Co.
We could state that:
CGIAR alone does increase capacities of the next product's user: e.g. CGIAR produces a new drought resistant variety and will provide it to seed Cies that multiply it for dissemination to farmers. CGIAR will develop the accompanying agronomic guidelines to plant & grow  it that will reach the farmers through training & communication with the support of local extension services. Farmers' communities will share the newly acquired knowledge. Extension services will communicate about the new variety.

so the result is reached by the CGIAR along is with its partners, intermediary bodies and farmers communities. Impact studies carried out several years after a project ended are very important to understand if the anticipated result was reached or not, at which %. The impact sutdy will be the evidence.

Elizabeth
________________________________

**Comment by Mttbnchtt** [comment]
@elizabetharnaud If I understand, you are saying that the CGIAR does not only improve capacities but also, collaborating with other, results of other types (like making agriculture more sustainable and mitigating climate change). Is that what you are saying?

Do you think that, then, we should change the label of the processes? Should the labels not merely be "process to develop the capacity to make agriculture more sustainable" but rather "process to make agriculture more sustainable"?

**Comment by Mttbnchtt** [comment]
If we say that process P _realizes some (concretizes some plan specification)_ and the plan specification is an IDO, then it seems wrong to say that the plan merely develops a capacity while the IDO is a tangible result. If the IDO is _enhance market access_, then it is not the case that the process _development of capacity to enhance market access_  realizes some (concretizes some plan specification). It seems that either we provide a different plan specification (either changing the label of the IDOs or adding new classes) or we change the label of the process.

**Comment by elizabetharnaud** [comment]
'Do you think that, then, we should change the label of the processes? Should the labels not merely be "process to develop the capacity to make agriculture more sustainable" but rather "process to make agriculture more sustainable"?'
We can have both as they are complementary and certainly along a timeline: First CGIAR improves capacity and then with strategic partners along the value chain, produces results which are impactful.

Elizabeth

________________________________

**Comment by Mttbnchtt** [comment]
Sounds good to me. I will check with @marieALaporte.

**Comment by Mttbnchtt** [comment]
We need process of both types:
- improving capacities
- obtaining concrete results. 

However, for now we focus on processes of the first type. Driven by the use-cases that we will receive, we will add processes of the second type as appropriate.
