### ISSUE TITLE
Create go to pages for PURLs

### ISSUE THREAD

**Issue by JMule** [SDG-InterfaceOntology/sdgio#26]
Hey,

Am Josephine, a developer.

Am figuring out who to create go to pages.....

The imported owl files should have more complete annotations which I can use to auto create each go to pages.

Thank you.

Regards,
Josephine

**Comment by cmungall** [comment]
Hi Josephine

Can you provide a little more context - what do you mean by a 'go to' page?

**Comment by JMule** [comment]
Hi Chris

Its a page that will hold details of a class in a user friendly way. Just transforming what is in the owl file. My request was whether we could have more details on the owl file, in addition to the label and id....my reference was the sdgio.owl file.

I hope this helps.

Thank you.

Regards,
Josephine

**Comment by pbuttigieg** [comment]
@cmungall These would be landing pages for the PURLs, something a little more user-friendly than OntoBee. 

@JMule - we can add more information as annotation attributes, what did you have in mind?

**Comment by JMule** [comment]
Dear Pier,

A brief description of the class, defination, subclasses/superclasses.

Thank you.

Regards,
Josephine

**Comment by pbuttigieg** [comment]
The definitions would be our main focus, but we can add a 'simple' definition and examples of usage for some classes.

**Comment by pbuttigieg** [comment]
@cmungall I believe the JMule's request asks for the retention of more annotations on the classes imported into SDGIO.  These will be parsed and presented on the landing pages. Right now, the definitions and comments may be useful.

**Comment by cmungall** [comment]
Remember, the how an ENVO or CHEBI or PATO purl resolves is outside the scope of this group. Currently these resolve to OntoBee, and the full set of annotations are included.

Of course, it's perfectly possible to have these classes display as desired within some kind of SDGIO portal, if that's the goal

**Comment by cmungall** [comment]
It might help to see specs/requirements for the portal to be able to plan accordingly
