### ISSUE TITLE
Format for Term Definitions

### ISSUE THREAD

**Issue by mark-jensen** [SDG-InterfaceOntology/sdgio#27]
Definitions should follow a consistent format. Currently we have either 

A [class label] is a(n) [superclass label] …
A(n) [superclass label] …

I propose adhering to the second as this is the most common format. There is no need to repeat the class name/label in the definition. 

The definition for ’sustainable development goal’ is
“A sustainable development goal is an objective specification which describes the endpoint of a development process following the Sustainable Development Agenda for 2030 plan specification”

would be changed to:
“An objective specification which describes the endpoint of a development process following the Sustainable Development Agenda for 2030 plan specification”

**Comment by pbuttigieg** [comment]
I'm happy either way. Removing the class label from the definition improves readability.

**Comment by cmungall** [comment]
+1
