### ISSUE TITLE
Set up development environment

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#3]
Imports:
Some are clear (e.g. BFO, ENVO, PCO, CHEBI, DO, IAO), but some will only become apparent later.
A mapping - guided by some text-mining - to GEMET and other such resources will help this.

**Comment by pbuttigieg** [comment]
Commits 12ae67a3c5a46cf6da138353c8d0507779245f4d and cef3c8e1d11d0d20c875448fc531d17ac79ebf4c have started the groundwork for the imports work flow. The PURLs in the seed files have to be changed to work with SDGIO.

**Comment by pbuttigieg** [comment]
Not sure why this was closed - still need to clear up makefile and finalise tests.

**Comment by pbuttigieg** [comment]
@cmungall notes that Travis and Jenkins jobs need to be set-up

**Comment by cmungall** [comment]
go to
https://github.com/SDG-InterfaceOntology/sdgio

<img width="937" alt="screen shot 2015-09-25 at 3 42 29 pm" src="https://cloud.githubusercontent.com/assets/50745/10113703/10d741d6-639c-11e5-8949-77530067c5b4.png">

you'll see the travis build passing symbol - unless someone commits a bad ontology

we have a jenkins job too
https://build.berkeleybop.org/job/build-sdgio

I'll keep both in parallel for a while but I think it will be better to switch to travis as it's more integrated with github

Think we're nearly ready to close this ticket?

**Comment by mark-jensen** [comment]
@pbuttigieg @cmungall Ok to close?

**Comment by cmungall** [comment]
+1
