### ISSUE TITLE
Added 'education'

### ISSUE THREAD

**Issue by mark-jensen** [SDG-InterfaceOntology/sdgio#36]
'education' = A planned process that has the specified objective to increase knowledge, obtain skills, and alter behavior.

A planned process with a specified objective because it is not clear if one can educate themselves accidentally. The objectives need refinement. 

Derived from SNOMEDCT
http://purl.bioontology.org/ontology/SNOMEDCT/409073007

**Comment by mark-jensen** [comment]
Eventually will need to add 'educational criteria' and 'educational institution', per indicators 4.3.1 & 12.8.1.

**Comment by pbuttigieg** [comment]
@phsmith noted that 
 `education process` is ambiguous and should be separated into two classes:
* educating process: the act of educating, dispensing education, etc
* 'being educated' process: receiving education

Thus:

### Definitions
* **'education'** = A planned process in which at least one educator has the specified objective to increase the knowledge and skill of at least one educatee or alter their behaviour.
 * an "educatee" is more specific than a 'learner' as learning can occur outside of an education process, which we assume has a plan.
* **'educating process'** = A part of an education process in which an educator imparts knowledge or skill to one or more educatees, or takes steps to alter their behaviour according to some plan.
 * In formal settings, the 'plan' could be a curriculum. In informal settings, we can be more generic.
* **'process of being educated'** = A planned process in which at least one educatee acquires knowledge and skill from at least one educator or has their behaviour modified by 
 * Perhaps we can find a more compact label
* **'education resource'** = A resource used during an education process which contributes to the realisation of that process' specified goals.
* **'educator'** = A human with an educator role.
* **'educator role'** = A role borne by an entity which imparts knowledge and skill to, or alters the behaviour of an educatee.
* **'educatee'** = A human with an educatee role
* **'educatee role'** = A role borne by an entity which receives knowledge and skill from, or whose behaviour is modified by, an educator.

### Further considerations
* Self-taught / autodidacts are a special consideration. The realise both the `educator role` and `educatee role`
* Formal and informal education must be differentiated

To phrase this in terms of production and consumption (cf. #16):
* An educator is a producer
* An educatee is a consumer
* A curriculum is a process plan with a resource role (consumption good)


### Extensions
UNESCO offers a definition of "education for sustainable development"
>“Education for Sustainable Development (ESD) is a learning process (or approach to teaching) based on the ideals and principles that underlie sustainability and is concerned with all levels and types of learning to provide quality education and foster sustainable human development – learning to know, learning to be, learning to live together, learning to do and learning to transform oneself and society.”

**Comment by mark-jensen** [comment]
@pbuttigieg @phismith

>'educating process' = A part of an education process in which an educator imparts knowledge or skill to one or more educatees, or takes steps to alter their behaviour according to some plan.

>'process of being educated' = A planned process in which at least one educatee acquires knowledge and skill, or has their behaviour modified by at least one educator.

Will these be subclasses as well as parts of some `education process`? If so, perhaps `education process` is simply a composition of one, or both.

**Comment by phismith** [comment]
The correct strategy for such cases is to define

whole education process

and then to define these as parts of whole education process

But that is somewhat ugly. I think just to define them as parts should be
enough.

I think the second definition should be the mirror image of the first
Also 'educatee' is a bit clumsy (and would need defining in a non-circular
way) which would be hard . I would suggest

education process' = a planned process in which knowledge or skill is
imparted'

'educating process' = A part of an education process in which a person
imparts knowledge or skill

'process of being educated' = A part of an education process in which one
person acquires knowledge or skill

Can you give me your argument for including 'or has their behaviour
modified'?
BS

**Comment by mark-jensen** [comment]
> education process' = a planned process in which knowledge or skill is
> imparted'
>
> 'educating process' = A part of an education process in which a person
> imparts knowledge or skill
>
> 'process of being educated' = A part of an education process in which one
> person acquires knowledge or skill
>

Shall all three of these be siblings under 'planned process'?​


> Can you give me your argument for including 'or has their behaviour
> modified'?
>

I think it should be dropped. Behavior being altered will follow from the
acquisition of knowledge and skills, but in itself is not the goal of
education.

Mark

BS

**Comment by phismith** [comment]
Yes
But then this should be added to the definitions, perhaps thus:

​
> 'educating process' = A part of an education process that is a planned
process in which a person
> imparts knowledge or skill
>
> 'process of being educated' = A part of an education process that is a
planned process in which one
> person acquires knowledge or skill

**Comment by mark-jensen** [comment]
The distinction between formal and informal still needs to addressed, that can happen in a different thread, since it will related to several classes (e.g., employment, education) and the solution will most likely carry between them all.

Closing for now.
