### ISSUE TITLE
Travis Failed a commit

### ISSUE THREAD

**Issue by mark-jensen** [SDG-InterfaceOntology/sdgio#43]
@cmungall 
I *think* because I had a class with two of same annotation properties.
Is that possible, and if so, should it be addressed as a bug? Sometimes more than one editor or comment is needed.

**Comment by cmungall** [comment]
Max one comment in obo format. We can relax this but why not just use a more specific AP?

**Comment by mark-jensen** [comment]
Good to know. No problem sticking to one comment per class.
