### ISSUE TITLE
slum and informal settlement

### ISSUE THREAD

**Issue by rlwalls2008** [SDG-InterfaceOntology/sdgio#50]
I think these should be subclasses of ENVO dense settlement biome. I will request the terms there, and link the issue here.

**Comment by rlwalls2008** [comment]
See EnvironmentOntology/envo#265 for informal settlement.

**Comment by rlwalls2008** [comment]
See EnvironmentOntology/envo#266 for slum

**Comment by pbuttigieg** [comment]
On it

**Comment by pbuttigieg** [comment]
cf. #41

**Comment by pbuttigieg** [comment]
I'm closing this issue for now. We've added the classes to start. Please reopen if needed.
