### ISSUE TITLE
Import OGMS 'disease'

### ISSUE THREAD

**Issue by mark-jensen** [SDG-InterfaceOntology/sdgio#55]
@cmungall 
We will need OGMS ['disease'](http://purl.obolibrary.org/obo/OGMS_0000031).

**Comment by cmungall** [comment]
Can you do the first part: add to imports/ogms_terms.txt

(you can do this via the github web interface, I recommend doing on a 
branch and making a PR)

This will all be better documented soon...

**Comment by mark-jensen** [comment]
My pleasure.

Although, thus far I've been committing directly to the master branch. Not best practice I guess...

**Comment by cmungall** [comment]
Actually, for anything to do with editing OWL files this is probably 
best, unless we very precisely coordinate Protege versions to avoid 
spurious diffs.
