### ISSUE TITLE
Export simple CSV-style inventory of terms as part of release process

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#62]
Update Makefile accordingly.

**Comment by cmungall** [comment]
Have a look at the sparql/ dir in envo, together with the lines 
referring to it in the makefile

**Comment by pbuttigieg** [comment]
Will do. Using that as a model.

**Comment by mark-jensen** [comment]
If it's required, we may want to also set in place a way to produce an updated collaborator file of prioritized terms. The current version is located [here]()

@cmungall pointed out that a way to capture the relevant indicators will need some thought if they are to be included in an automated build. 

Some discussion about modeling the indicators already exists in

**Comment by pbuttigieg** [comment]
Initial run of the basic report (class label, definition, and PURL) and the edge list committed in https://github.com/SDG-InterfaceOntology/sdgio/commit/115051be0552fe016be2b58f9dddbfb0ddf61de5. 
Available [here](https://github.com/SDG-InterfaceOntology/sdgio/tree/master/src/reports)

SPARQL files [here](https://github.com/SDG-InterfaceOntology/sdgio/tree/master/src/sparql)

The relevant lines have been uncommented in the Makefile.

:warning: **Issues **:warning: 
@cmungall 
 * The labels of the "subject" class in the [edge list](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/reports/sdgio-edges.csv#L2) are missing and I can't figure out why, especially since the object class labels are fine. The [statement for the subject class](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/sparql/edges.sparql#L20) is pretty much the same as [that of the object class](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/sparql/edges.sparql#L21), is it the SPARQL magic above it?
 * The [basicReport](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/reports/sdgio-basicReport.csv) reflects the fact that we don't import all the definitions from external ontologies. I think we should. There are also some weird lines with nothing but strings like " _:b5" in the classID field. Any idea what these are

**Comment by mark-jensen** [comment]
@pbuttigieg @cmungall Can this be closed?

I posted a new issue at #100 for making the change to JSON.
