### ISSUE TITLE
Represent 'ownership'

### ISSUE THREAD

**Issue by pdez90** [SDG-InterfaceOntology/sdgio#67]
Hi, 'ownership' is also one the priority terms that need to be defined in the SDGIO.

Usage in the SDGIO.
SDG 5.a: Undertake reforms to give women equal rights to economic resources, as well as access and control over land, and other forms of property, financial services, inheritance and natural resources, in accordance with national laws.

SDG 5.a.1: a) Percentage of people with ownership or secure rights over agricultural land (out of total agricultural population, by sex; and b) Share of women among owners or rights-bearers of agricultural land, by type of tenure

SDG 5.a.2: The legal framework includes special measures to guarantee women's equal rights to land ownership and control

Do let me know if clarification from a domain specialist is required.

**Comment by mark-jensen** [comment]
@pdez90 please make sure to search existing issues before creating new threads. Thank you. 
Closing this and transferring your comments to #54
