### ISSUE TITLE
Represent 'employed/unemployed'

### ISSUE THREAD

**Issue by pdez90** [SDG-InterfaceOntology/sdgio#68]
These are also priority terms that need to be represented in the SDGIO. Employment is not currently represented in the SDGIO

Related terms: informal-formal

Context: Refers to the formal and informal sector. Refers to education: 4.3.1-adult participation in formal and non formal education- 12.8.1 formal and informal education curricula
Gray indicator 8.10.2 adults with a formal account or personally using a mobile money service

**Comment by mark-jensen** [comment]
Closing and moving comments to #37
