### ISSUE TITLE
Represent 'carbon emissions'

### ISSUE THREAD

**Issue by pdez90** [SDG-InterfaceOntology/sdgio#76]
Priority term to be defined in the SDGIO

Context:
9.4.1: Carbon emissions per unit of value added

**Comment by mark-jensen** [comment]
https://github.com/EnvironmentOntology/envo/issues/280

**Comment by mark-jensen** [comment]
@pdez90 Did you see the indicator has changed to read:
> CO2 emission per unit of value added. 

Does that change the term request? 'carbon emission' appears nowhere else in the indicators or targets.

**Comment by pdez90** [comment]
Hi, I spoke to Lud. CO2 emissions makes more sense. Thanks for pointing
that out Mark!

On Wed, Jan 27, 2016 at 12:22 AM, Mark Jensen <notifications@github.com>
wrote:

> @pdez90 <https://github.com/pdez90> Did you see the indicator has changed
> to read:
>
> CO2 emission per unit of value added.
>
> Does that change the term request? 'carbon emission' appears nowhere else
> in the indicators or targets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SDG-InterfaceOntology/sdgio/issues/76#issuecomment-175235842>
> .
>



-- 
Yours Sincerely,
Priyanka deSouza

**Comment by mark-jensen** [comment]
Closed with addition of ENVO `carbon dioxide emission process` and `carbon dioxide emission`.
