### ISSUE TITLE
Edge table bugs

### ISSUE THREAD

**Issue by pbuttigieg** [SDG-InterfaceOntology/sdgio#96]
The [edge table export](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/reports/sdgio-edges.csv) isn't populating some fields. This is probably due to poor SPARQLing on my part. The SPARQL file is [here](https://github.com/SDG-InterfaceOntology/sdgio/blob/master/src/sparql/edges.sparql).

@cmungall would you be able to intervene here?

**Comment by cmungall** [comment]
your sparql is fine - arq doesn't follow imports. Easiest thing to do is make a merged file to query over, will handle that shortly

**Comment by cmungall** [comment]
We really need the equivalent of perl's "use strict" for sparql queries...
